### ISSUE TITLE
Mix of ICD-10 and ICD-10-CM codes

### ISSUE THREAD

**Issue by james-skelton** [monarch-initiative/mondo-ingest#11]
I'm a researcher in the UK using MONDO as part of a study, and I can't seem to figure out which version of ICD-10 is being used by MONDO. 

For example, http://purl.obolibrary.org/obo/MONDO_0018378 is osteonecrosis of the jaw and cross-references to K10 -- in ICD-10, this is correct, but in ICD-10-CM this should (probably) be M87. Additionally, I'm not sure K10 exists in ICD-10-CM. Conversely, http://purl.obolibrary.org/obo/MONDO_0001752 is alveolar periostitis, and cross-references to M27 (which doesn't exist in ICD-10, as far as I can tell). 

Any advice would be great!

**Comment by joeflack4** [comment]
It seems that for my work on checking quality here, it sounds like we're wanting to get rid of all ICD10 prefixes in favor of ICD10CM vs ICD10PS, since I heard that ICD10 == ICD10CM. I also "verified" this online:

> From: https://www.datafied.com/faqs/what-is-the-difference-between-icd-10-cm-and-icd10/#:~:text=There%20is%20no%20difference%20between,healthcare%20establishments%20in%20the%20U.S.
> There is no difference between ICD 10 CM and ICD 10. In fact, when most people are talking about ICD-10, they are speaking of ICD-10CM. ICD-10CM is the medical coding set for diagnosis coding and is used in all healthcare establishments in the U.S.
> ICD-10PCS, on the other hand, is the code set that is used in the hospital inpatient settings. It is designed for inpatient coding and is much more accurate and specific.

But what Harold appears to have said is that either ICD10 is (a) also an ontology, separate from ICD10XM and ICD10PS. But it appears that probably that is not the case and, rather, it's the case that (b) ICD10 and its concept codes that have less digits in them, represents more of a generalization. That is, they're more like "abstract classes", and that the actual concepts / concrete classes are found in either ICD10CM or ICD10PS, and inherit from ICD10, but that doesn't mean that ICD10 has actual concrete concepts of its own that are distinct from these ontologies.

Hopefully my understanding is correct. But when Harold says that "_ICD-10-CM subsumes (mostly... there are cases where it alters the semantics of ICD-10) ICD-10_", I'm hoping that this means that the semantics of ICD10 being different simply means that they're more abstract (as I alluded to in my previous paragraph), as opposed to concepts with actual different meanings.

@hsolbrig If you want to elaborate on this, feel free. I'm about to start work on this issue as a precursor for some ICD::Mondo mapping work.

**Comment by joeflack4** [comment]
Related issue: #15

**Comment by matentzn** [comment]
Closing in favour of https://github.com/monarch-initiative/mondo/issues/4651
