### ISSUE TITLE
Mapping: should not be done on exact synonym of type abbreviation

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#230]
from https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/lexmatch/unmapped_doid_lex.tsv

Some (but not all) matches are made on exact synonym of type abbreviation and are incorrect. 
--> maybe we should not have this rule when matching

examples: 

subject_id | subject_label | predicate_id | object_id | object_label | mapping_justification | mapping_tool | confidence | subject_match_field | object_match_field | match_string | comment
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MONDO:0018922 | cold agglutinin disease | MONDO:equivalentTo | DOID:0111275 | speech-language disorder-1 | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | oio:hasExactSynonym | cas | LEXMATCH
MONDO:0013162 | autosomal recessive limb-girdle muscular dystrophy type 2N | MONDO:equivalentTo | DOID:0112382 | muscular dystrophy-dystroglycanopathy type C8 | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | oio:hasExactSynonym | mddgc2 | LEXMATCH
MONDO:0003917 | heart lymphoma | MONDO:equivalentTo | DOID:0070212 | hereditary lymphedema I | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | oio:hasExactSynonym | pcl | LEXMATCH
MONDO:0018689 | plasma cell leukemia | MONDO:equivalentTo | DOID:0070212 | hereditary lymphedema I | semapv:LexicalMatching | oaklib | 0.8 | oio:hasExactSynonym | oio:hasExactSynonym | pcl | LEXMATCH

**Comment by matentzn** [comment]
Rather than to add a synonymiser rule, maybe can delete all abbreviations from mondo prior to processing, this will drastically reduce false positives. 

Basically take this goal: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/mondo-ingest.Makefile#L372

and add 

`remove --term "http://purl.obolibrary.org/obo/mondo#ABBREVIATION"` in the ROBOT clause right after the `merge` clause.
