### ISSUE TITLE
add MONDO:excludeAllergy exclusion code

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#237]
A new exclusion code was created and used in an exclusion list: **MONDO:excludeAllergy**

This code was added in the table [here](https://docs.google.com/spreadsheets/d/18V-_j4b22LzCytxFEM3pBEl6-_ODJY06gpUwH0F6JVY/edit#gid=1644570180) and [here](https://mondo.readthedocs.io/en/latest/editors-guide/exclusion-reasons/#exclusion-reasons) (please check this only after https://github.com/monarch-initiative/mondo/pull/6071 has been merged)

@joeflack4 : I don't know whether you need to add this new code somewhere in your import code. Please let me know 
(1) if it needs to be added somewhere, 
(2) if I can add it myself or if I need to let you know (especially moving forward), (
3) if there is anything else you need. 
Thanks!

**Comment by joeflack4** [comment]
Hey @sabrinatoro, thanks for being proactive about this.

To my understanding, there's actually nothing I need to do on my end / the `mondo-ingest`. This code (or any exclusion code) can be freely used in any of the `src/ontology/config/*_exclusions.tsv`, or anywhere else in `mondo-ingest`. There's no part of `mondo-ingest` that validates these codes. No errors will occur; even if it's not a valid code. 

@matentzn Correct me if I'm wrong but I'm pretty sure this is the case, unless there is some kind of validation on this that you want me to add. Otherwise I think we can close this issue.
