### ISSUE TITLE
Terms in unmapped components dont show up in slurp files

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#303]
Examples are below:
Orphanet:522574
Orphanet:522576
Orphanet:522584

A full list is in this [spreadsheet](https://docs.google.com/spreadsheets/d/1DTedQy0B19XtDWa9O0WePL5SztHL_R_HzphoAwywwwE/edit#gid=0)

cc @nicolevasilevsky @sabrinatoro

**Comment by joeflack4** [comment]
Oh, OK. I'm assuming these are both unmapped and also valid slurp candidates. I will look into this this week.

**Comment by joeflack4** [comment]
@matentzn It looks like the[ slurp integrity analysis](https://docs.google.com/spreadsheets/d/1kc_RGzdRye7nnCLKYpG0DBKTBQxgezd_0MjJell1Q2c/edit#gid=1042657882) I did is coming handy here as well. I'm going to keep that branch alive locally, but I wonder if this output would be good for us to simply commit as well.

For the 3 terms that you listed, all of them have been excluded from slurp because not all of their parents are mapped.

I just updated the [slurp docs](https://github.com/monarch-initiative/mondo-ingest/pull/316#discussion_r1198457048) to include all of the conditions:
> To be migratable, the term (i) must not already be mapped, (ii) must not be excluded (e.g. not in `reports/%_term_exclusions.txt`), and (iii) must not be deprecated / obsolete. Then, (iv) there are conditions concerning its parents. It must either (a) have no parents, or (b) have no valid parents in Mondo (i.e. all of its parent terms are marked obsolete in Mondo), or (c) **all its parents must be mapped**, and at least 1 of those parent's mappings must be one of `skos:exactMatch` or `skos:NarrowMatch`.

Can you confirm that 'all parents mapped' should indeed be a condition?

Also, can we maybe replace / supplement `%-unmapped.owl` files with `%-migratable.owl`? Unmapped != slurpable/migratable. I also was using another term "mappable unmapped", but I think that is likely to cause more confusion as well since by that I actually meant something in between unmapped and migratable...

**Comment by matentzn** [comment]
I think its safer if _all_ parents, if they exist, are either mapped or deprecated in Mondo.

**Comment by joeflack4** [comment]
The phrasing and maybe the logic is a bit wonky and needing changed, but I think that's how it is. If the parent is deprecated in Mondo, that means it's mapped.
