### ISSUE TITLE
Which terms outside the current term scopes are xref'd?

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#31]
I would like to know which terms outside the term scope of the Mondo source alignment are xrefed in Mondo. 

### Background:

- Mondo ingest sources like ORDO, OMIM and ICD10CM are not aligned in their entirety - just the "relevant part". For example, we do not try to align all of NCIT - just the disease branch. We use sparql to select the "relevant terms" to extract, for example https://github.com/monarch-initiative/mondo-ingest/blob/main/src/sparql/ncit-relevant-signature.sparql
- These queries are potentially overpruning, i.e. removing concepts that can be usefully aligned with Mondo (although this should not be the case).
- To get a sense where we are missing stuff, I would like to know if there are Mondo classes that are linked to classes outside that "relevant" scope.

### Inputs:

- Mondo mappings: https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mappings/mondo.sssom.tsv
- all the signature files in the report directory (can be rerun with `sh run.sh make signature_reports`).
 
Process:

- Create read all the signature files, the mapping files.
- Figure out which classes that are in `reports/mirror_signature-%.tsv` but not in `reports/component_signature-%.tsv` are in the mondo mapping file.
- This may require some prefix mapping stuff which you should be able to get from the prefix map in the Mondo mapping file.

**Comment by joeflack4** [comment]
Ok, makes sense to me so far. I'll prioritize this after a couple other tickets.

## Questions
1. **Where to put the analysis?**: Recently I created an `analyses/` / `analysis/` directory in OMIM. I like this better than `scripts/`, because that can be very broad. If you agree with this, then I wonder if it would make sense to repurpose the `mondo-analysis` repo, moving mondo-related analyses (or everything) into `mondo` or `mondo-ingest` repos, and then maybe renaming the repo `mondo-paper(s)` or something.
2. Is there an error in this sentence?: 
> Figure out which classes that are in reports/mirror_signature-%.tsv but not in reports/component_signature-%.tsv are in the mondo mapping file.
Did you mean:
> a. Figure out which classes that are in reports/mirror_signature-%.tsv **and** reports/component_signature-%.tsv **that are not in** the mondo mapping file.
> b. Figure out which classes that are in reports/mirror_signature-%.tsv but not in reports/component_signature-%.tsv **or the** mondo mapping file.

**Comment by matentzn** [comment]
i am fine with adding `src/analysis` in mondo-ingest as well.

2. No error: I added all the files in here as well: https://github.com/monarch-initiative/mondo-ingest/tree/main/src/ontology/reports

Which classes that (are in `reports/mirror_signature-%.tsv` but not in `reports/component_signature-%.tsv`) **are in the mondo.sssom.tsv mapping file**?

**Comment by matentzn** [comment]
Did you update the actual tables as well?

**Comment by joeflack4** [comment]
@matentzn I only ran a new update for ORDO, since I think that was the only one that had a recent change. Here's the new [summary table](https://github.com/monarch-initiative/mondo-ingest/pull/35#issuecomment-1183726790):

|ontology|n_in1_notIn2_in3|pct_in1_notIn2_in3__over_in1|
|--------|----------------|----------------------------|
|ordo    |624            |0.0408                      |
|ncit    |166             |0.001                       |
|doid    |14               |0.001                         |
|icd10cm |0               |0.0                         |
|icd10who|0               |0.0                         |
|omim    |0               |0.0                         |

Much less! It was ~5,000 before.

The reports, by ontology are found here: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/
Merged report here: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/reports/excluded_terms_in_mondo_xrefs.tsv
