### ISSUE TITLE
OMIM ingest: "TYPE" in the omim label is replaced with "iia"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo-ingest#472]
In slurp/omim.tsv, the labels coming from OMIM are updated (for capitalization,...), but "TYPE" is incorrectly updated to "iia". 
For example: 
These 2 lines from omim.tsv:
MONDO:0958222	maple syrup urine disease,  iia 1b	OMIM:620698	MONDO:equivalentTo	maple syrup urine disease,  **iia** 1b		
MONDO:0958223	maple syrup urine disease,  iia 2	OMIM:620699	MONDO:equivalentTo	maple syrup urine disease,  **iia** 2		

The corresponding labels in OMIM are, and should be
MAPLE SYRUP URINE DISEASE, **TYPE** IB
MAPLE SYRUP URINE DISEASE, **TYPE** II

**Comment by joeflack4** [comment]
Found the issue!

There's a bug in this `known_capitalizations.tsv` configuration file.
|lower_name|cap_name|pattern|
|-|-|-|
|type|2|xtype 2X %[ ]type 2x%|
|type| iia|type IIA %[ ]type, iia%|

I changed it to:
|lower_name|cap_name|pattern|
|-|-|-|
|type 2x|type 2X %[ ]type 2x%| |
|type iia|type IIA %[ ]type, iia%| |

I don't remember where / who I originally got this file from, but either way it is now fixed in
