### ISSUE TITLE
Bug in Subclass Sync: Missing evidence in "confirmed" table

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/mondo-ingest#708]
See comment here: https://github.com/monarch-initiative/mondo/pull/8432#issuecomment-2493386699

## _Bug_: 

There are 

- pairs of Mondo classes with a direct subclass relation
- both exact matches to DOID
- ...but the subclass relation _does not appear in the [list of confirmed subclasses](https://raw.githubusercontent.com/monarch-initiative/mondo-ingest/main/src/ontology/reports/sync-subClassOf.confirmed.tsv) (`reports/sync-subClassOf.confirmed.tsv`)_.

## Example:

```
[Term]
id: MONDO:0000248
name: dengue shock syndrome
xref: DOID:0050125 {source="MONDO:equivalentTo"}
is_a: MONDO:0005502 {source="DOID:0050125", source="MONDO:Redundant"} ! dengue disease
```

```
[Term]
id: MONDO:0005502
name: dengue disease
xref: DOID:12205 {source="MONDO:equivalentTo", source="EFO:0005547"}
```

And in DO:

```
<owl:Class rdf:about="http://purl.obolibrary.org/obo/DOID_0050125">
    <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_12205"/>
    <rdfs:label xml:lang="en">dengue shock syndrome</rdfs:label>
</owl:Class>
```

The confirmed subclass table is clearly missing this, only containing these two entries related to dengue:

```
MONDO:0005358	Dengue hemorrhagic fever	MONDO:0005502	DOID:12206	DOID:12205	dengue disease
MONDO:0000259	asymptomatic dengue	MONDO:0005502	DOID:0050143	DOID:12205	dengue disease
```

In my opinion its a bug in the subclass sync, one that we didn't notice because my previous subclass pipeline didn't delete _all_ the evidence.

**Comment by joeflack4** [comment]
@matentzn In https://github.com/monarch-initiative/mondo/pull/8432#issuecomment-2493386699 you noticed a SCR (subclass relation) not showing up as expected in the `-confirmed` in subclass sync.

The missing relation as it appears in `mondo-edit.obo` is:
```
[Term]
id: MONDO:0000248
is_a: MONDO:0005502 {source="DOID:0050125", source="MONDO:Redundant"} ! dengue disease
```

Notice the `MONDO:Redundant`. This is because this SCR is inferred. It is not a direct SCR, which is what is supposed to show up in `-confirmed`.

So I think there is no issue here. Do you agree?

If so, does any QC need to be updated to ignore such cases? Or do we just have to remember that we still have inferred axioms appearing in `mondo-edit.obo`?

**Comment by joeflack4** [comment]
@matentzn This is the first time I'm hearing about a `reasoned, non-reduced version of mondo-edit`.

**What's currently going on**
`mondo-ingest` is set up to produce `mondo.owl` and `mondo.sssom.tsv` via the `build_mondo` func. That `mondo.owl` is the same `mondo.owl` in the `mondo` repo. The prereq for that is `reasoned.owl` (`$(ONT).owl: reasoned.owl`)

```
reasoned.owl: filtered.owl
	$(ROBOT) reason -T true -x true -X true -i $< -r ELK relax reduce -p false -r ELK \
		remove --term MONDO:0700097 --term OGMS:0000031 $(ANN) -o $@
```

The inferred SCR still shows up in `filtered.owl`, but not in `reasoned.owl`. I'm unfamiliar with most of the nuance in most of these robot options, but at least one of them is responsible for removing the inferred axioms.

**What to do?**
Is there some other artefact I'm supposed to depend on? The `reasoned, non-reduced version of mondo-edit`? What is that file actually called?

Perhaps it is created as a prereq and is already being generated by `build_mondo`. That would be good. Otherwise, we'd have to modify `build_mondo` to produce it as well.

**Comment by joeflack4** [comment]
Also, it looks like we had planned to do "direct in source, but indirect in mondo" as "priority 3", and I think this is one of the cases that we just didn't get to yet. It is described in [the google doc](https://docs.google.com/document/d/1H8fJKiKD-L1tfS-2LJu8t0_2YXJ1PQJ_7Zkoj7Vf7xA/edit?tab=t.0).

**Comment by matentzn** [comment]
https://github.com/monarch-initiative/mondo-ingest/pull/607?

**Comment by joeflack4** [comment]
@matentzn I completely forgot / barely remember this PR!

I investigated and here's my latest comment:
- https://github.com/monarch-initiative/mondo-ingest/pull/607#discussion_r1861348261

It might be better to discuss further on [slack](https://monarchinitiative.slack.com/archives/C03AW548J8M/p1732573109401759), or better yet, if there is no rush, and since it is Thanksgiving in the US, I'd prefer to discuss at next Monday's `mondo-ingest` call.

**Comment by twhetzel** [comment]
The PR for this is merged into `develop` so this is effectively Done so closing.
