### ISSUE TITLE
MONDO IDs must have 7 digits

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#96]
@joeflack4 for slurping, you currently expert six digit MONDO ids. All MONDO ids must be padded to seven digits. For example, `MONDO:800000` should be `MONDO:0800000`. Make sure the numeric value respects the id range I have assigned to the slurp.

**Comment by joeflack4** [comment]
Ah, no problem.

I actually had pre-written the code to do this. I just commented it out because, given the `min_id` we wee passing, it didn't look like it would ever come up that we'd need any padding. Although I guess if we run it with a lower `min_id`, we might need the padding.

I just uncommented out that line and opened a PR: https://github.com/monarch-initiative/mondo-ingest/pull/97#pullrequestreview-1135083678

@matentzn Want me to re-run the slurp on this? My memory on this tells me that that none of the assigned IDs will change though because the `min_id` is already high enough, but I haven't looked at this in a while, so I could be wrong. Of course you are also free to merge as is.

**Comment by matentzn** [comment]
The current Ids are all in the 800K range, so they will all be padded by a zero!

Yes, when the PR is merged, please rerun the slurp. I am currently making a new release, so don't run it before Monday :D

**Comment by matentzn** [comment]
Release done. https://github.com/monarch-initiative/mondo-ingest/releases/tag/v2022-10-08

This also fixes the ORDO sublcass issue.

**Comment by joeflack4** [comment]
IDK why I thought that I expected 6 digits instead of 7. I remember looking into it though. Weird. 

Ahh man, I gotta re-run the slurp again ;_;. Ok will do.

@matentzn Because we have two open PRs, both slurp related, I'll need some way of merging before I re-run the slurp. Therefore I'll merge #97 first, since it's a one-liner change, then I'll rebase my other slurp PR #100.
